options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Sync static site files to GCS bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - '-m'
    - 'rsync'
    - '-r'
    - '-d'
    - '.'
    - 'gs://varun-static-site-484410'
